In [5]:
### Author:  Daniel Lagos
# Date:  Sept 29, 2022

In [8]:
# import libraries
import numpy as np

In [9]:
an_array = np.array([3, 33, 333])

print (an_array)
print(type(an_array))

[  3  33 333]
<class 'numpy.ndarray'>


In [14]:
array_Two = np.array([[11, 12, 123], [21, 22, 23]])
print(array_Two)
print(array_Two.shape)

[[ 11  12 123]
 [ 21  22  23]]
(2, 3)
